Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,117 +34,118 @@ jobs:
       - name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
         
-  terraform:
-    needs: build
-    name: 'Terraform'
-    runs-on: ubuntu-latest
-    if: ${{ !contains(github.event.head_commit.message, '/destroy') && !contains(github.event.head_commit.message, '/apply')}}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-          
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}        
-          
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
-        
-      - name: Terraform Init
-        id: init
-        run: terraform init
-        
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
-        
-      - name: Terraform Plan
-        id: plan        
-        run: terraform plan -no-color
-        continue-on-error: true
-        
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-        
-      - name: Terraform Apply        
-        run: terraform apply -auto-approve
-  terraform-apply:
-    name: 'Terraform-Apply'
-    runs-on: ubuntu-latest
-    if: ${{contains(github.event.head_commit.message, '/apply')}}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
-          
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}        
-          
-      - name: Terraform Format
-        id: fmt
-        run: terraform fmt -check
-        
-      - name: Terraform Init
-        id: init
-        run: terraform init
-        
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
-        
-      - name: Terraform Plan
-        id: plan        
-        run: terraform plan -no-color
-        continue-on-error: true
-        
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-        
-      - name: Terraform Apply        
-        run: terraform apply -auto-approve
-        
-  terraform-destroy:    
-    name: 'Terraform-Destroy'
-    runs-on: ubuntu-latest
-    if: ${{ contains(github.event.head_commit.message, '/destroy') }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-        
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-2
-          
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}        
-
-      - name: Terraform Init
-        id: init
-        run: terraform init
-                  
-      - name: Terraform Destroy        
-        run: terraform destroy -auto-approve
+#  terraform:
+#    needs: build
+#    name: 'Terraform'
+#    runs-on: ubuntu-latest
+#    if: ${{ !contains(github.event.head_commit.message, '/destroy') && !contains(github.event.head_commit.message, '/apply')}}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#        
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-region: us-east-1
+#          
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v1
+#        with:
+#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}        
+#          
+#      - name: Terraform Format
+#        id: fmt
+#        run: terraform fmt -check
+#        
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#        
+#      - name: Terraform Validate
+#        id: validate
+#        run: terraform validate -no-color
+#        
+#      - name: Terraform Plan
+#        id: plan        
+#        run: terraform plan -no-color
+#        continue-on-error: true
+#        
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
+#        
+#      - name: Terraform Apply        
+#        run: terraform apply -auto-approve
+#  terraform-apply:
+#    name: 'Terraform-Apply'
+#    runs-on: ubuntu-latest
+#    if: ${{contains(github.event.head_commit.message, '/apply')}}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#        
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-region: us-east-1
+#          
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v1
+#        with:
+#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}        
+#          
+#      - name: Terraform Format
+#        id: fmt
+#        run: terraform fmt -check
+#        
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#        
+#      - name: Terraform Validate
+#        id: validate
+#        run: terraform validate -no-color
+#        
+#      - name: Terraform Plan
+#        id: plan        
+#        run: terraform plan -no-color
+#        continue-on-error: true
+#        
+#      - name: Terraform Plan Status
+#        if: steps.plan.outcome == 'failure'
+#        run: exit 1
+#        
+#      - name: Terraform Apply        
+#        run: terraform apply -auto-approve
+#        
+#  terraform-destroy:    
+#    name: 'Terraform-Destroy'
+#    runs-on: ubuntu-latest
+#    if: ${{ contains(github.event.head_commit.message, '/destroy') }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#        
+#      - name: Configure AWS Credentials
+#        uses: aws-actions/configure-aws-credentials@v1
+#        with:
+#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#          aws-region: us-east-2
+#          
+#      - name: Setup Terraform
+#        uses: hashicorp/setup-terraform@v1
+#        with:
+#          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}        
+#
+#      - name: Terraform Init
+#        id: init
+#        run: terraform init
+#                  
+#      - name: Terraform Destroy        
+#        run: terraform destroy -auto-approve
+#
